#!/usr/bin/env python3

# PyCosworth - a datastream logger and digital dashboard display interface for
# Magneti Marelli ECU modules as used on the Ford Sierra/Escort Cosworth as
# well as OBDII engine interface systems.
# Copyright (C) 2018  John Snowdon
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Standard libraries
import multiprocessing
import time
import sys
import os

# Settings file
from libs import settings

# ECU data storage structure
from libs.EcuData import EcuData

# Any worker methods
from iomodules.SensorIO import SensorIO
from iomodules.ConsoleIO import ConsoleIO
from iomodules.GPIOButtonIO import GPIOButtonIO
from iomodules.GraphicsIO import GraphicsIO
from iomodules.DataLoggerIO import DataLoggerIO

# Start a new logger
from libs.newlog import newlog
if getattr(sys, 'frozen', False):
	__file__ = os.path.dirname(sys.executable)
logger = newlog(__file__)

def sensorWorker(dataQueue, controlQueue):
	""" Runs the sensor IO process to send and receive data from the ECU and any other sensors """
	SensorIO(dataQueue, controlQueue)
	
def consoleWorker(ecudata):
	""" Print sensor data to the terminal screen """
	ConsoleIO(ecudata)

def graphicsWorker(ecudata, controlQueue):
	""" Output sensor data to display devices """
	GraphicsIO(ecudata, controlQueue)

def gpioButtonWorker(actionQueue, stdin):
	""" Output sensor data to a Matrix Orbital text mode LCD """
	GPIOButtonIO(actionQueue, stdin)

def dataLoggerWorker(ecudata, dataQueue, actionQueue):
	""" Records incoming sensor data to disk """
	DataLoggerIO(ecudata, dataQueue, actionQueue)

#####################################################
#
# Add any user-defined worker functions here
# e.g.
#
# def myWorkerProcess(ecudata):
#	""" Do something else with the data """
#	myWorker(ecudata)
#
######################################################

if __name__ == '__main__':
	
	# A new ecu data structure
	dataManager = multiprocessing.Manager()
	ecuDataDict = dataManager.dict()
	ecuStatusDict = dataManager.dict()
	ecuSensorDict = dataManager.dict()
	ecuCounter = multiprocessing.Value('d', 0)
	ecuSampleTime = multiprocessing.Value('d', 0.0)
	ecuErrors = multiprocessing.Array('i', range(settings.MAX_ERRORS))
	
	# Create a new ecudata class using the shared data structures from above
	ecuData = EcuData(ecuDataDict = ecuDataDict, 
		ecuSensorDict = ecuSensorDict,
		ecuCounter = ecuCounter, 
		ecuErrors = ecuErrors, 
		ecuSampleTime = ecuSampleTime, 
		ecuStatusDict = ecuStatusDict)
			
	# A list of all worker processes
	workers = []

	# A list of all control queues
	messageQueues = []
	datalogger_listeners = []
	
	# Start the Sensor IO process
	sensorDataQueue = multiprocessing.Queue() # Passes data back up from the sensors themselves
	sensorControlQueue = multiprocessing.Queue() # Takes messages to start/stop ecu comms, enable/disable demo mode, etc
	sensor_p = multiprocessing.Process(target=sensorWorker, args=(sensorDataQueue, sensorControlQueue))
	sensor_p.start()
	workers.append(sensor_p)
	messageQueues.append(sensorControlQueue)
	
	###########################################################
	#
	# This block is where you add any workers that you also
	# want to have access to the sensor data returned from the ECU
	
	# Start the console IO process
	if settings.USE_CONSOLE:
		# The Console worker has a control queue that it listens for incoming control
		# messages on.
		console_p = multiprocessing.Process(target=consoleWorker, args=(ecuData))
		console_p.start()
		workers.append(console_p)
    
    # Start the process to capture Raspberry Pi GPIO button presses
	if settings.USE_BUTTONS:
		# The GPIO/Button worker has an action queue that it PUTS message onto,
		# but it DOESNT need to access the ecuData data structure.
		gpioDataQueue = multiprocessing.Queue() # passes messages back up (button 1 pressed, etc)
		my_stdin = sys.stdin.fileno()
		gpio_button_p = multiprocessing.Process(target=gpioButtonWorker, args=(gpioDataQueue, my_stdin))
		gpio_button_p.start()
		workers.append(gpio_button_p)
      
    # Start the OLED/SDL graphics process
	if settings.USE_GRAPHICS:
		# The OLED/SDL worker has a control queue that it listens for incoming
		# control messages on.
		graphicsControlQueue = multiprocessing.Queue() # Takes messages (change sensor, show that ecu is disconnected, etc)
		matrix_p = multiprocessing.Process(target=graphicsWorker, args=(ecuData, graphicsControlQueue))
		matrix_p.start()
		workers.append(matrix_p)
		messageQueues.append(graphicsControlQueue) # we want the gfx display to listen for messages from input devices
		datalogger_listeners.append(graphicsControlQueue) # we want the gfx display to listen for messages from the logger
	
	# Start the data logger process
	if settings.USE_DATALOGGER:
		# The logger worker has a control queue that it listens for incoming
		# control messages on.
		loggerControlQueue = multiprocessing.Queue() # takes messages (start the logger, stop the logger, etc)
		loggerDataQueue = multiprocessing.Queue() # passes messages back up (logger stopped/started, disk error, etc)
		logger_p = multiprocessing.Process(target=dataLoggerWorker, args=(ecuData, loggerDataQueue, loggerControlQueue))
		logger_p.start()
		workers.append(logger_p)
		messageQueues.append(loggerControlQueue) # we want the logger to listen for messages from input devices
    
	# Start gathering data
	i = 0
	while True:
		
		if i == 10000:
			logger.debug("Still running [main process]")
			i = 0
		# Get latest data  
		# If the receive queue has any data back...
		#if sensorReceiveQueue.empty() == False:
		
		try:
			if sensorDataQueue.empty() == False:
				d = sensorDataQueue.get(block = True, timeout = 0.01)
				logger.debug("Got some sensor data")
				sensorDataType = d[0] # d0 = message_type
				sensorData = d[1] # d1 = sensorData dict
				loopCount = d[2] # d2 = sensor loop count
				timerData = d[3] # d4 = time taken for last data collection cycle
				
				# Check for type of the data
				if sensorDataType == settings.TYPE_ERROR:
					# We do special things for error messages
					logger.warn("Error message received")
					ecuData.addError(d[2])
				elif sensorDataType == settings.TYPE_DATA:
					# But for anything else we record it as a sensor value
					ecuData.setCounter(loopCount)
					ecuData.setSensorData(sensorData['sensor'])
					ecuData.setData(sensorData['sensor']['sensorId'], sensorData['value'], timerData, loopCount)
				elif sensorDataType == settings.TYPE_STATUS:
					# A status update - failed connection, enable/disable demo, ecu error, etc
					# Pass it on to the graphics display so it can work out what to show to the user
					graphicsControlQueue.put(sensorData)
				else:
					logger.warn("Unknown message type from SensorIO process")
			
		except Exception as e:
			logger.error("%s" % e)
			pass
		
		# Check for any GPIO/keyboard button message
		if gpioDataQueue.empty() == False:
			logger.debug("Message in the input control queue [%d]" % gpioDataQueue.qsize())
			gpioMessage = gpioDataQueue.get()
			# Distribute the messages to all processes
			# so that each process (apart from gpio) can decide what to do with it
			for q in messageQueues:
				q.put(gpioMessage)
		
		# Message passed back up from the data logger class
		if loggerDataQueue.empty() == False:
			logger.debug("Message from data logger [%d]" % loggerDataQueue.qsize())
			loggerMessage = loggerDataQueue.get()
			# Put it in all queues (apart from the graphics one)
			for q in datalogger_listeners:
				q.put(loggerMessage)			
		
		i += 1
    
	# Wait for the workers to finish
	sensorTransmitQueue.close()
	sensorTransmitQueue.join_thread()
	sensorReceiveQueue.close()
	sensorReceiveQueue.join_thread()
	masterActionQueue.close()
	masterActionQueue.join_thread()
	loggerActionQueue.close()
	loggerActionQueue.join_thread()
	
	for q in messageQueues:
		q.close()
		q.join_thread()
	
	for w in workers:
		w.join()
